site_name: test
site_url: https://systemc.org/

repo_url: https://github.com/accellera-official/

theme:
  name: mkdocs
  custom_dir: overrides/
  nav_style: light

extra_css:
  - stylesheets/extra.css

nav:
- Home: index.md
- Overview:
    - SystemC: overview/systemc.md
    - SystemC TLM: overview/systemc-tlm.md
    - SystemC AMS: overview/systemc-ams.md
    - SystemC CCI: overview/systemc-cci.md
    - SystemC Verification: overview/systemc-verification.md
    - SystemC Common Practices (SCP): overview/systemc-scp.md
#- Documentation:
#    - SystemC: docs/systemc/documentation.md
- Events:
    - SystemC Events: events/scevents.md
    - SystemC Evolution Fika - May 2024: events/scef202405.md
    - SystemC Evolution Fika - February 2024: events/scef202402.md
    - SystemC Evolution Fika - September 2023: events/scef202309.md
    - SystemC Evolution Fika - September 2022: events/scef202209.md
    - SystemC Evolution Fika - April 2022: events/scef202204.md
    - SystemC Evolution Fika - June 2021: events/scef202106.md
    - SystemC Evolution Fika - March 2021: events/scef202103.md
    - SystemC Evolution Day 2024: events/sced2024.md
    - SystemC Evolution Day 2023: events/sced2023.md
    - SystemC Evolution Day 2022: events/sced2022.md
    - SystemC Evolution Day 2021: events/sced2021.md
    - SystemC Evolution Day 2020: events/sced2020.md
    - SystemC Evolution Day 2019: events/sced2019.md
    - SystemC Evolution Day 2018: events/sced2018.md
    - SystemC Evolution Day 2017: events/sced2017.md
    - SystemC Evolution Day 2016: events/sced2016.md
- Resources:
    - Books: resources/books.md
    - Discussion forum: https://forums.accellera.org/forum/9-systemc/
    - Education: resources/education.md
    - Libraries & Projects: resources/projects.md
    - Open Access Publications: resources/publications.md
    - Standards & Implementations: resources/standards.md
    - Tools: resources/tools.md
    - Training: resources/training.md
    - Videos: resources/videos.md
- Playground: https://www.edaplayground.com/x/56Q4
- Get Involved: get-involved.md
